version: '3.8'

services:
  db:
    image: postgres:13.7-alpine3.16
    env_file:
      - ./config/.local.env
    ports:
      - '5432:5432'
    volumes: 
      - ./postgres_data:/var/lib/postgresql/data